# Generated by Django 3.1 on 2020-08-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='city',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
