# Generated by Django 3.1 on 2020-08-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbapp', '0003_sector_subsector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsector',
            name='subSectors',
            field=models.CharField(max_length=50),
        ),
    ]
